version: 1.0.{build}
image: Ubuntu
environment:
  matrix:
    - BUILD_CONFIGURATION: Debug
    - BUILD_CONFIGURATION: Release
build_script:
  - cmake -G "Clion" -A x64 -DCMAKE_BUILD_TYPE=%BUILD_CONFIGURATION% .
  - cmake --build . --config %BUILD_CONFIGURATION%