# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'windows-latest'
variables:
  BUILD_TYPE: 'release'

steps:
- task: CMake@1 # Use the CMake task
  displayName: 'Configure CMake'
  inputs:
    cmakeListPath: 'CMakeLists.txt' # Path to your CMakeLists.txt
    buildType: '$(BUILD_TYPE)'
    cmakeOptions: '-DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)' # Set install directory

- task: VSBuild@1 # Use the Visual Studio Build task (for MSBuild, use MSBuild@1)
  displayName: 'Build'
  inputs:
    #solution: '**/*.sln' # Path to your solution file (if using MSBuild)
    platform: 'x64'
    configuration: '$(BUILD_TYPE)'

- task: PublishBuildArtifacts@1 # Publish build artifacts
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'pipeline'
