# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # Use an Ubuntu agent

variables:
  BUILD_TYPE: 'Release'

steps:
- task: CMake@1
  displayName: 'Configure CMake'
  inputs:
    cmakeListPath: 'CMakeLists.txt'
    buildType: '$(BUILD_TYPE)'
    cmakeOptions: '-DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)' # Important for publishing

- script: |
    cmake --build . --config $(BUILD_TYPE)
  displayName: 'Build'
  env:
    CC: gcc # Explicitly set the C compiler
    CXX: g++ # Explicitly set the C++ compiler

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'pipeline'
